export const AIRPORTS = [
  { iata_code: "LHR", airport_name: "Heathrow Airport", city_name: "London", country_name: "United Kingdom" },
  { iata_code: "LGW", airport_name: "Gatwick Airport", city_name: "London", country_name: "United Kingdom" },
  { iata_code: "STN", airport_name: "Stansted Airport", city_name: "London", country_name: "United Kingdom" },
  { iata_code: "MAN", airport_name: "Manchester Airport", city_name: "Manchester", country_name: "United Kingdom" },
  { iata_code: "EDI", airport_name: "Edinburgh Airport", city_name: "Edinburgh", country_name: "United Kingdom" },
  { iata_code: "CDG", airport_name: "Charles de Gaulle Airport", city_name: "Paris", country_name: "France" },
  { iata_code: "ORY", airport_name: "Orly Airport", city_name: "Paris", country_name: "France" },
  { iata_code: "NCE", airport_name: "Nice Côte d'Azur Airport", city_name: "Nice", country_name: "France" },
  { iata_code: "FRA", airport_name: "Frankfurt Airport", city_name: "Frankfurt", country_name: "Germany" },
  { iata_code: "MUC", airport_name: "Munich Airport", city_name: "Munich", country_name: "Germany" },
  { iata_code: "BER", airport_name: "Berlin Brandenburg Airport", city_name: "Berlin", country_name: "Germany" },
  { iata_code: "DUS", airport_name: "Düsseldorf Airport", city_name: "Düsseldorf", country_name: "Germany" },
  { iata_code: "HAM", airport_name: "Hamburg Airport", city_name: "Hamburg", country_name: "Germany" },
  { iata_code: "AMS", airport_name: "Amsterdam Schiphol Airport", city_name: "Amsterdam", country_name: "Netherlands" },
  { iata_code: "BRU", airport_name: "Brussels Airport", city_name: "Brussels", country_name: "Belgium" },
  { iata_code: "MAD", airport_name: "Adolfo Suárez Madrid–Barajas Airport", city_name: "Madrid", country_name: "Spain" },
  { iata_code: "BCN", airport_name: "Barcelona–El Prat Airport", city_name: "Barcelona", country_name: "Spain" },
  { iata_code: "AGP", airport_name: "Málaga Airport", city_name: "Málaga", country_name: "Spain" },
  { iata_code: "FCO", airport_name: "Leonardo da Vinci–Fiumicino Airport", city_name: "Rome", country_name: "Italy" },
  { iata_code: "MXP", airport_name: "Milan Malpensa Airport", city_name: "Milan", country_name: "Italy" },
  { iata_code: "VCE", airport_name: "Venice Marco Polo Airport", city_name: "Venice", country_name: "Italy" },
  { iata_code: "ZRH", airport_name: "Zurich Airport", city_name: "Zurich", country_name: "Switzerland" },
  { iata_code: "GVA", airport_name: "Geneva Airport", city_name: "Geneva", country_name: "Switzerland" },
  { iata_code: "VIE", airport_name: "Vienna International Airport", city_name: "Vienna", country_name: "Austria" },
  { iata_code: "CPH", airport_name: "Copenhagen Airport", city_name: "Copenhagen", country_name: "Denmark" },
  { iata_code: "OSL", airport_name: "Oslo Gardermoen Airport", city_name: "Oslo", country_name: "Norway" },
  { iata_code: "ARN", airport_name: "Stockholm Arlanda Airport", city_name: "Stockholm", country_name: "Sweden" },
  { iata_code: "HEL", airport_name: "Helsinki-Vantaa Airport", city_name: "Helsinki", country_name: "Finland" },
  { iata_code: "LIS", airport_name: "Humberto Delgado Airport", city_name: "Lisbon", country_name: "Portugal" },
  { iata_code: "OPO", airport_name: "Francisco Sá Carneiro Airport", city_name: "Porto", country_name: "Portugal" },
  { iata_code: "ATH", airport_name: "Athens Eleftherios Venizelos Airport", city_name: "Athens", country_name: "Greece" },
  { iata_code: "PRG", airport_name: "Václav Havel Airport Prague", city_name: "Prague", country_name: "Czech Republic" },
  { iata_code: "WAW", airport_name: "Warsaw Chopin Airport", city_name: "Warsaw", country_name: "Poland" },
  { iata_code: "BUD", airport_name: "Budapest Ferenc Liszt Airport", city_name: "Budapest", country_name: "Hungary" },
  { iata_code: "OTP", airport_name: "Henri Coandă International Airport", city_name: "Bucharest", country_name: "Romania" },
  { iata_code: "SOF", airport_name: "Sofia Airport", city_name: "Sofia", country_name: "Bulgaria" },
  { iata_code: "IST", airport_name: "Istanbul Airport", city_name: "Istanbul", country_name: "Turkey" },
  { iata_code: "SAW", airport_name: "Istanbul Sabiha Gökçen Airport", city_name: "Istanbul", country_name: "Turkey" },
  { iata_code: "AYT", airport_name: "Antalya Airport", city_name: "Antalya", country_name: "Turkey" },
  { iata_code: "JFK", airport_name: "John F. Kennedy International Airport", city_name: "New York", country_name: "United States" },
  { iata_code: "LGA", airport_name: "LaGuardia Airport", city_name: "New York", country_name: "United States" },
  { iata_code: "EWR", airport_name: "Newark Liberty International Airport", city_name: "Newark", country_name: "United States" },
  { iata_code: "LAX", airport_name: "Los Angeles International Airport", city_name: "Los Angeles", country_name: "United States" },
  { iata_code: "ORD", airport_name: "O'Hare International Airport", city_name: "Chicago", country_name: "United States" },
  { iata_code: "MDW", airport_name: "Chicago Midway International Airport", city_name: "Chicago", country_name: "United States" },
  { iata_code: "ATL", airport_name: "Hartsfield–Jackson Atlanta International Airport", city_name: "Atlanta", country_name: "United States" },
  { iata_code: "DFW", airport_name: "Dallas/Fort Worth International Airport", city_name: "Dallas", country_name: "United States" },
  { iata_code: "MIA", airport_name: "Miami International Airport", city_name: "Miami", country_name: "United States" },
  { iata_code: "SFO", airport_name: "San Francisco International Airport", city_name: "San Francisco", country_name: "United States" },
  { iata_code: "SEA", airport_name: "Seattle-Tacoma International Airport", city_name: "Seattle", country_name: "United States" },
  { iata_code: "BOS", airport_name: "Logan International Airport", city_name: "Boston", country_name: "United States" },
  { iata_code: "IAD", airport_name: "Washington Dulles International Airport", city_name: "Washington D.C.", country_name: "United States" },
  { iata_code: "DEN", airport_name: "Denver International Airport", city_name: "Denver", country_name: "United States" },
  { iata_code: "LAS", airport_name: "Harry Reid International Airport", city_name: "Las Vegas", country_name: "United States" },
  { iata_code: "PHX", airport_name: "Phoenix Sky Harbor International Airport", city_name: "Phoenix", country_name: "United States" },
  { iata_code: "MCO", airport_name: "Orlando International Airport", city_name: "Orlando", country_name: "United States" },
  { iata_code: "YYZ", airport_name: "Toronto Pearson International Airport", city_name: "Toronto", country_name: "Canada" },
  { iata_code: "YVR", airport_name: "Vancouver International Airport", city_name: "Vancouver", country_name: "Canada" },
  { iata_code: "YUL", airport_name: "Montréal–Trudeau International Airport", city_name: "Montreal", country_name: "Canada" },
  { iata_code: "YYC", airport_name: "Calgary International Airport", city_name: "Calgary", country_name: "Canada" },
  { iata_code: "MEX", airport_name: "Benito Juárez International Airport", city_name: "Mexico City", country_name: "Mexico" },
  { iata_code: "CUN", airport_name: "Cancún International Airport", city_name: "Cancún", country_name: "Mexico" },
  { iata_code: "GRU", airport_name: "São Paulo–Guarulhos International Airport", city_name: "São Paulo", country_name: "Brazil" },
  { iata_code: "GIG", airport_name: "Rio de Janeiro–Galeão International Airport", city_name: "Rio de Janeiro", country_name: "Brazil" },
  { iata_code: "EZE", airport_name: "Ministro Pistarini International Airport", city_name: "Buenos Aires", country_name: "Argentina" },
  { iata_code: "SCL", airport_name: "Arturo Merino Benítez International Airport", city_name: "Santiago", country_name: "Chile" },
  { iata_code: "BOG", airport_name: "El Dorado International Airport", city_name: "Bogotá", country_name: "Colombia" },
  { iata_code: "LIM", airport_name: "Jorge Chávez International Airport", city_name: "Lima", country_name: "Peru" },
  { iata_code: "DXB", airport_name: "Dubai International Airport", city_name: "Dubai", country_name: "United Arab Emirates" },
  { iata_code: "AUH", airport_name: "Abu Dhabi International Airport", city_name: "Abu Dhabi", country_name: "United Arab Emirates" },
  { iata_code: "DOH", airport_name: "Hamad International Airport", city_name: "Doha", country_name: "Qatar" },
  { iata_code: "KWI", airport_name: "Kuwait International Airport", city_name: "Kuwait City", country_name: "Kuwait" },
  { iata_code: "BAH", airport_name: "Bahrain International Airport", city_name: "Manama", country_name: "Bahrain" },
  { iata_code: "MCT", airport_name: "Muscat International Airport", city_name: "Muscat", country_name: "Oman" },
  { iata_code: "RUH", airport_name: "King Khalid International Airport", city_name: "Riyadh", country_name: "Saudi Arabia" },
  { iata_code: "JED", airport_name: "King Abdulaziz International Airport", city_name: "Jeddah", country_name: "Saudi Arabia" },
  { iata_code: "TLV", airport_name: "Ben Gurion International Airport", city_name: "Tel Aviv", country_name: "Israel" },
  { iata_code: "AMM", airport_name: "Queen Alia International Airport", city_name: "Amman", country_name: "Jordan" },
  { iata_code: "BEY", airport_name: "Rafic Hariri International Airport", city_name: "Beirut", country_name: "Lebanon" },
  { iata_code: "CAI", airport_name: "Cairo International Airport", city_name: "Cairo", country_name: "Egypt" },
  { iata_code: "HRG", airport_name: "Hurghada International Airport", city_name: "Hurghada", country_name: "Egypt" },
  { iata_code: "SSH", airport_name: "Sharm el-Sheikh International Airport", city_name: "Sharm el-Sheikh", country_name: "Egypt" },
  { iata_code: "CMN", airport_name: "Mohammed V International Airport", city_name: "Casablanca", country_name: "Morocco" },
  { iata_code: "RAK", airport_name: "Marrakech Menara Airport", city_name: "Marrakech", country_name: "Morocco" },
  { iata_code: "TUN", airport_name: "Tunis-Carthage International Airport", city_name: "Tunis", country_name: "Tunisia" },
  { iata_code: "ALG", airport_name: "Houari Boumediene Airport", city_name: "Algiers", country_name: "Algeria" },
  { iata_code: "JNB", airport_name: "O.R. Tambo International Airport", city_name: "Johannesburg", country_name: "South Africa" },
  { iata_code: "CPT", airport_name: "Cape Town International Airport", city_name: "Cape Town", country_name: "South Africa" },
  { iata_code: "NBO", airport_name: "Jomo Kenyatta International Airport", city_name: "Nairobi", country_name: "Kenya" },
  { iata_code: "ADD", airport_name: "Addis Ababa Bole International Airport", city_name: "Addis Ababa", country_name: "Ethiopia" },
  { iata_code: "LOS", airport_name: "Murtala Muhammed International Airport", city_name: "Lagos", country_name: "Nigeria" },
  { iata_code: "ACC", airport_name: "Kotoka International Airport", city_name: "Accra", country_name: "Ghana" },
  { iata_code: "DEL", airport_name: "Indira Gandhi International Airport", city_name: "New Delhi", country_name: "India" },
  { iata_code: "BOM", airport_name: "Chhatrapati Shivaji Maharaj International Airport", city_name: "Mumbai", country_name: "India" },
  { iata_code: "BLR", airport_name: "Kempegowda International Airport", city_name: "Bengaluru", country_name: "India" },
  { iata_code: "HYD", airport_name: "Rajiv Gandhi International Airport", city_name: "Hyderabad", country_name: "India" },
  { iata_code: "MAA", airport_name: "Chennai International Airport", city_name: "Chennai", country_name: "India" },
  { iata_code: "CCU", airport_name: "Netaji Subhas Chandra Bose International Airport", city_name: "Kolkata", country_name: "India" },
  { iata_code: "AMD", airport_name: "Sardar Vallabhbhai Patel International Airport", city_name: "Ahmedabad", country_name: "India" },
  { iata_code: "COK", airport_name: "Cochin International Airport", city_name: "Kochi", country_name: "India" },
  { iata_code: "PNQ", airport_name: "Pune Airport", city_name: "Pune", country_name: "India" },
  { iata_code: "GOI", airport_name: "Goa International Airport", city_name: "Goa", country_name: "India" },
  { iata_code: "PEK", airport_name: "Beijing Capital International Airport", city_name: "Beijing", country_name: "China" },
  { iata_code: "PKX", airport_name: "Beijing Daxing International Airport", city_name: "Beijing", country_name: "China" },
  { iata_code: "PVG", airport_name: "Shanghai Pudong International Airport", city_name: "Shanghai", country_name: "China" },
  { iata_code: "SHA", airport_name: "Shanghai Hongqiao International Airport", city_name: "Shanghai", country_name: "China" },
  { iata_code: "CAN", airport_name: "Guangzhou Baiyun International Airport", city_name: "Guangzhou", country_name: "China" },
  { iata_code: "SZX", airport_name: "Shenzhen Bao'an International Airport", city_name: "Shenzhen", country_name: "China" },
  { iata_code: "CTU", airport_name: "Chengdu Tianfu International Airport", city_name: "Chengdu", country_name: "China" },
  { iata_code: "HKG", airport_name: "Hong Kong International Airport", city_name: "Hong Kong", country_name: "Hong Kong" },
  { iata_code: "TPE", airport_name: "Taiwan Taoyuan International Airport", city_name: "Taipei", country_name: "Taiwan" },
  { iata_code: "ICN", airport_name: "Incheon International Airport", city_name: "Seoul", country_name: "South Korea" },
  { iata_code: "GMP", airport_name: "Gimpo International Airport", city_name: "Seoul", country_name: "South Korea" },
  { iata_code: "NRT", airport_name: "Narita International Airport", city_name: "Tokyo", country_name: "Japan" },
  { iata_code: "HND", airport_name: "Haneda Airport", city_name: "Tokyo", country_name: "Japan" },
  { iata_code: "KIX", airport_name: "Kansai International Airport", city_name: "Osaka", country_name: "Japan" },
  { iata_code: "SIN", airport_name: "Singapore Changi Airport", city_name: "Singapore", country_name: "Singapore" },
  { iata_code: "KUL", airport_name: "Kuala Lumpur International Airport", city_name: "Kuala Lumpur", country_name: "Malaysia" },
  { iata_code: "BKK", airport_name: "Suvarnabhumi Airport", city_name: "Bangkok", country_name: "Thailand" },
  { iata_code: "DMK", airport_name: "Don Mueang International Airport", city_name: "Bangkok", country_name: "Thailand" },
  { iata_code: "HKT", airport_name: "Phuket International Airport", city_name: "Phuket", country_name: "Thailand" },
  { iata_code: "CNX", airport_name: "Chiang Mai International Airport", city_name: "Chiang Mai", country_name: "Thailand" },
  { iata_code: "CGK", airport_name: "Soekarno–Hatta International Airport", city_name: "Jakarta", country_name: "Indonesia" },
  { iata_code: "DPS", airport_name: "Ngurah Rai International Airport", city_name: "Bali", country_name: "Indonesia" },
  { iata_code: "MNL", airport_name: "Ninoy Aquino International Airport", city_name: "Manila", country_name: "Philippines" },
  { iata_code: "SGN", airport_name: "Tan Son Nhat International Airport", city_name: "Ho Chi Minh City", country_name: "Vietnam" },
  { iata_code: "HAN", airport_name: "Noi Bai International Airport", city_name: "Hanoi", country_name: "Vietnam" },
  { iata_code: "DAD", airport_name: "Da Nang International Airport", city_name: "Da Nang", country_name: "Vietnam" },
  { iata_code: "RGN", airport_name: "Yangon International Airport", city_name: "Yangon", country_name: "Myanmar" },
  { iata_code: "PNH", airport_name: "Phnom Penh International Airport", city_name: "Phnom Penh", country_name: "Cambodia" },
  { iata_code: "REP", airport_name: "Siem Reap–Angkor International Airport", city_name: "Siem Reap", country_name: "Cambodia" },
  { iata_code: "CMB", airport_name: "Bandaranaike International Airport", city_name: "Colombo", country_name: "Sri Lanka" },
  { iata_code: "KTM", airport_name: "Tribhuvan International Airport", city_name: "Kathmandu", country_name: "Nepal" },
  { iata_code: "DAC", airport_name: "Hazrat Shahjalal International Airport", city_name: "Dhaka", country_name: "Bangladesh" },
  { iata_code: "KHI", airport_name: "Jinnah International Airport", city_name: "Karachi", country_name: "Pakistan" },
  { iata_code: "LHE", airport_name: "Allama Iqbal International Airport", city_name: "Lahore", country_name: "Pakistan" },
  { iata_code: "ISB", airport_name: "Islamabad International Airport", city_name: "Islamabad", country_name: "Pakistan" },
  { iata_code: "KBL", airport_name: "Kabul International Airport", city_name: "Kabul", country_name: "Afghanistan" },
  { iata_code: "SYD", airport_name: "Sydney Kingsford Smith Airport", city_name: "Sydney", country_name: "Australia" },
  { iata_code: "MEL", airport_name: "Melbourne Airport", city_name: "Melbourne", country_name: "Australia" },
  { iata_code: "BNE", airport_name: "Brisbane Airport", city_name: "Brisbane", country_name: "Australia" },
  { iata_code: "PER", airport_name: "Perth Airport", city_name: "Perth", country_name: "Australia" },
  { iata_code: "ADL", airport_name: "Adelaide Airport", city_name: "Adelaide", country_name: "Australia" },
  { iata_code: "AKL", airport_name: "Auckland Airport", city_name: "Auckland", country_name: "New Zealand" },
  { iata_code: "CHC", airport_name: "Christchurch Airport", city_name: "Christchurch", country_name: "New Zealand" },
  { iata_code: "SVO", airport_name: "Sheremetyevo International Airport", city_name: "Moscow", country_name: "Russia" },
  { iata_code: "DME", airport_name: "Domodedovo International Airport", city_name: "Moscow", country_name: "Russia" },
  { iata_code: "LED", airport_name: "Pulkovo Airport", city_name: "Saint Petersburg", country_name: "Russia" },
  { iata_code: "GYD", airport_name: "Heydar Aliyev International Airport", city_name: "Baku", country_name: "Azerbaijan" },
  { iata_code: "TBS", airport_name: "Tbilisi International Airport", city_name: "Tbilisi", country_name: "Georgia" },
  { iata_code: "EVN", airport_name: "Zvartnots International Airport", city_name: "Yerevan", country_name: "Armenia" },
  { iata_code: "ALA", airport_name: "Almaty International Airport", city_name: "Almaty", country_name: "Kazakhstan" },
  { iata_code: "TAS", airport_name: "Tashkent International Airport", city_name: "Tashkent", country_name: "Uzbekistan" },
];
