export const BLOG_DATA = {
  posts: [
    {
      img: "/image/blog/blog-1.png",
      date: "20 March 2024",
      comment: "3 Comment",
      title: "Charter flight of the Death Penalty in America",
      text: "With a vast array of popular private planes to choose from, travelling by private jet charter is the most efficient.",
      url: "/blog-details",
    },
    {
      img: "/image/blog/blog-2.png",
      date: "23 February 2024",
      comment: "4 Comment",
      title: "Our technology consistently delivers",
      text: "Private jet hire for leisure purposes allows yourself, your family and friends to travel in luxury, comfort and privacy.",
      url: "/blog-details",
    },
    {
      img: "/image/blog/blog-3.png",
      date: "18 June 2024",
      comment: "6 Comment",
      title: "Search the world with ease and transparency",
      text: "It’s fast gaining in popularity as leisure time becomes increasingly precious and we value the experience of the journey.",
      url: "/blog-details",
    },
    {
      img: "/image/blog/blog-1.png",
      date: "20 March 2024",
      comment: "1 Comment",
      title: "Charter an entire jet, or offer the seats",
      text: "Whether it’s a short trip for a weekend skiing or a two-week holiday in the Caribbean, we’ll help you choose.",
      url: "/blog-details",
    },
    {
      img: "/image/blog/blog-1.png",
      date: "10 March 2024",
      comment: "4 Comment",
      title: "XO is not simply a private jet service.",
      text: "Your loved ones to your destination in comfort and with minimal fuss. Access to private terminals also helps you.",
      url: "/blog-details",
    },
    {
      img: "/image/blog/blog-2.png",
      date: "16 March 2024",
      comment: "2 Comment",
      title: "As well as getting to fly to many different",
      text: "Bstle of busy airports and queues through security, well-rested and ready to make the most of your next adventure.",
      url: "/blog-details",
    },
  ],
  sidebar: {
    recentPosts: [
      {
        img: "/image/blog/small-blog-1.png",
        date: "Aug 23,2021",
        title: "Charter flight of the Death Penalty in America",
        url: "/blog-details",
      },
      {
        img: "/image/blog/small-blog-2.png",
        date: "Aug 23,2021",
        title: "Our technology consistently delivers",
        url: "/blog-details",
      },
      {
        img: "/image/blog/small-blog-3.png",
        date: "Aug 23,2021",
        title: "Search the world with ease and transparency",
        url: "/blog-details",
      },
      {
        img: "/image/blog/small-blog-4.png",
        date: "Aug 23,2021",
        title: "Charter an entire jet, or offer the seats",
        url: "/blog-details",
      },
    ],
    categories: [
      { name: "Business Analysis", count: 4 },
      { name: "Business Strategy", count: 5 },
      { name: "Stock Investment", count: 1 },
      { name: "Business Analysis", count: 4 },
      { name: "Business Analysis", count: 4 },
      { name: "Business Analysis", count: 4 },
    ],
    tags: [
      "Airport",
      "Private Jet",
      "Helicopter",
      "Gallery",
      "Corporate",
      "Business",
    ],
  },
};
