export const FLEET_CATEGORIES = [
  "All",
  "Light Jet",
  "Midsize Jet",
  "Super Midsize",
  "Heavy Jet",
  "Ultra Long Range",
  "VIP Airliner",
];

export const FLEET_PLANES = [
  {
    id: "phenom-300e",
    name: "Embraer Phenom 300E",
    category: "Light Jet",
    image: "/image/av/jet-flying.webp",
    overview: "The Phenom 300E is the best-selling light jet in the world, renowned for its range, speed, and class-leading cabin space and comfort.",
    specs: {
      passengers: 8,
      range: 2010,
      speed: 464,
      luggage: 84,
      cabinHeight: "4.9 ft",
      cabinWidth: "5.1 ft",
      cabinLength: "17.2 ft",
    },
    features: ["Class-Leading Cabin Comfort", "Stunning In-Flight Performance", "Spacious Internal Baggage Compartment"],
  },
  {
    id: "citation-xls-plus",
    name: "Cessna Citation XLS+",
    category: "Light Jet",
    image: "/image/av/jet-stairs.webp",
    overview: "Combining midsize luxury and amenities with light jet agility and operating efficiency, the XLS+ features a generous stand-up cabin and comfortable seating.",
    specs: {
      passengers: 9,
      range: 2100,
      speed: 441,
      luggage: 90,
      cabinHeight: "5.7 ft",
      cabinWidth: "5.5 ft",
      cabinLength: "18.5 ft",
    },
    features: ["Stand-Up Cabin (5.7 ft)", "Bespoke In-Flight Refreshment Bar", "Generous External Luggage Capacity"],
  },
  {
    id: "gulfstream-g280",
    name: "Gulfstream G280",
    category: "Midsize Jet",
    image: "/image/av/jet-sunset.webp",
    overview: "The Gulfstream G280 is a midsize high-performer that redefines cabin comfort, fuel efficiency, and safety. Its low cabin altitude leaves you feeling refreshed.",
    specs: {
      passengers: 9,
      range: 3600,
      speed: 482,
      luggage: 120,
      cabinHeight: "6.1 ft",
      cabinWidth: "6.1 ft",
      cabinLength: "25.8 ft",
    },
    features: ["Quiet Cabin Technology", "Best-In-Class Fuel Efficiency", "Low Cabin Altitude Control"],
  },
  {
    id: "challenger-350",
    name: "Bombardier Challenger 350",
    category: "Super Midsize",
    image: "/image/av/jet-night.webp",
    overview: "The Challenger 350 defines the super-midsize category. It offers the optimal combination of range, cabin space, speed, and runway versatility.",
    specs: {
      passengers: 10,
      range: 3200,
      speed: 470,
      luggage: 106,
      cabinHeight: "6.0 ft",
      cabinWidth: "7.2 ft",
      cabinLength: "25.2 ft",
    },
    features: ["Completely Flat Floor Cabin", "Advanced Sound Reduction Panels", "Exceptional Short-Runway Agility"],
  },
  {
    id: "gulfstream-g550",
    name: "Gulfstream G550",
    category: "Heavy Jet",
    image: "/image/av/jet-dusk-blue.jpg",
    overview: "The Gulfstream G550 is a legendary heavy jet built for intercontinental flight. With flexible living spaces, it remains a favorite for VIP global travelers.",
    specs: {
      passengers: 16,
      range: 6750,
      speed: 488,
      luggage: 170,
      cabinHeight: "6.2 ft",
      cabinWidth: "7.3 ft",
      cabinLength: "50.1 ft",
    },
    features: ["Up to Four Distinct Living Areas", "High-Speed In-Flight Internet", "Signature Oval Windows with Bright Sunlight"],
  },
  {
    id: "global-7500",
    name: "Bombardier Global 7500",
    category: "Ultra Long Range",
    image: "/image/av/jet-gold-hero.png",
    overview: "The Global 7500 is the largest and longest-range business jet ever built, offering a kitchen, crew suite, and four true living areas for ultimate luxury.",
    specs: {
      passengers: 19,
      range: 7700,
      speed: 516,
      luggage: 195,
      cabinHeight: "6.2 ft",
      cabinWidth: "8.0 ft",
      cabinLength: "54.4 ft",
    },
    features: ["Four True Living Spaces", "Dedicated Crew & Galley Zones", "Ultra-Smooth FlexWing Design"],
  },
  {
    id: "boeing-bbj",
    name: "Boeing Business Jet (BBJ)",
    category: "VIP Airliner",
    image: "/image/av/new-plane.jpg",
    overview: "Based on commercial airliners, the BBJ offers an unparalleled volume of space. It can be configured with private bedrooms, showers, and conference rooms.",
    specs: {
      passengers: 30,
      range: 6200,
      speed: 470,
      luggage: 640,
      cabinHeight: "7.1 ft",
      cabinWidth: "11.6 ft",
      cabinLength: "79.1 ft",
    },
    features: ["Residential Scale Private Bedroom", "Fully En-Suite Shower & Bath", "Grand Boardroom & Dining Tables"],
  },
];
